# Generated by Django 6.0.1 on 2026-02-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_cover_image_alter_book_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
