# Generated by Django 6.0.1 on 2026-02-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_cover_image_alter_book_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pdf_file_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
